/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.softech_escritorio;



import com.mycompany.Categoria.FormCategoria;
import com.mycompany.crud_clientes.FormCliente;
import com.mycompany.marca.crud_marca;
import com.mycompany.productos.*;
import java.awt.Font;
import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author XDemo
 */
public class FormInicio extends javax.swing.JFrame {

    /**
     * Creates new form FormInicio
     */
    public FormInicio() {
        initComponents();
        Font montserratFont = new Font("Montserrat", Font.PLAIN, 12);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel bg = new javax.swing.JPanel();
        javax.swing.JPanel sidepanel = new javax.swing.JPanel();
        javax.swing.JButton productosButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JButton marcasButton = new javax.swing.JButton();
        javax.swing.JButton categoriasButton = new javax.swing.JButton();
        javax.swing.JButton clientesButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setMaximumSize(new java.awt.Dimension(0, 0));
        bg.setPreferredSize(new java.awt.Dimension(0, 0));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepanel.setBackground(new java.awt.Color(61, 157, 217));
        sidepanel.setMaximumSize(new java.awt.Dimension(0, 0));
        sidepanel.setMinimumSize(new java.awt.Dimension(340, 650));
        sidepanel.setPreferredSize(new java.awt.Dimension(0, 0));
        sidepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productosButton.setBackground(new java.awt.Color(148, 215, 242));
        productosButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        productosButton.setText("Productos");
        productosButton.setBorder(null);
        productosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosButtonActionPerformed(evt);
            }
        });
        sidepanel.add(productosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 330, 100));

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("____________________________________________");
        sidepanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 340, 20));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Menú");
        sidepanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 150, -1));

        marcasButton.setBackground(new java.awt.Color(188, 232, 243));
        marcasButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        marcasButton.setText("Marcas");
        marcasButton.setBorder(null);
        marcasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcasButtonActionPerformed(evt);
            }
        });
        sidepanel.add(marcasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 330, 100));

        categoriasButton.setBackground(new java.awt.Color(188, 232, 243));
        categoriasButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        categoriasButton.setText("Categorias");
        categoriasButton.setBorder(null);
        categoriasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasButtonActionPerformed(evt);
            }
        });
        sidepanel.add(categoriasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 330, 100));

        clientesButton.setBackground(new java.awt.Color(188, 232, 243));
        clientesButton.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        clientesButton.setText("Clientes");
        clientesButton.setBorder(null);
        clientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesButtonActionPerformed(evt);
            }
        });
        sidepanel.add(clientesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 330, 100));

        bg.add(sidepanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 542));

        jPanel1.setBackground(new java.awt.Color(61, 157, 217));
        jPanel1.setMaximumSize(new java.awt.Dimension(0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Softech Escritorio");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 490, -1));

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 70, -1, 109));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 940, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesButtonActionPerformed
        FormCliente objetoCliente = new FormCliente();
        objetoCliente.setVisible(true);
        objetoCliente.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        objetoCliente.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_clientesButtonActionPerformed

    private void marcasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcasButtonActionPerformed
        crud_marca objetoCrud = new crud_marca();
        objetoCrud.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        objetoCrud.setExtendedState(JFrame.MAXIMIZED_BOTH);
        objetoCrud.setVisible(true);
    }//GEN-LAST:event_marcasButtonActionPerformed

    private void categoriasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasButtonActionPerformed
        FormCategoria objetoCategoria = new FormCategoria();
        objetoCategoria.setVisible(true);
        objetoCategoria.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        objetoCategoria.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_categoriasButtonActionPerformed

    private void productosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosButtonActionPerformed
        FormProductos objetoProductos = new FormProductos();
        objetoProductos.setVisible(true);
        objetoProductos.setExtendedState(JFrame.MAXIMIZED_BOTH);
        objetoProductos.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_productosButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
